#spring:
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.SunOneJtaPlatform
#      org.hibernate.envers.table_creation: CREATE
#      org.hibernate.envers.audit_table_suffix: _AUD
#      # org.hibernate.envers.audit_table_prefix: audit_schema
#      org.hibernate.envers.revision_field_name: revision_id
#      org.hibernate.envers.revision_type_field_name: revision_type
