spring:
  config:
    import: optional:classpath:application-shared-${spring.profiles.active}.yaml

server:
  port: 8080

app:
  security:
    allowed-origins: "*"

# OpenAPI Server Configuration
springdoc:
  server:
    test:
      url: https://test-krava.degra.lv
