spring:
  jpa:
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
server:
  port: 8080

app:
  security:
    allowed-origins: "http://localhost:8081"


keycloak:
  auth-server-url: https://route.degra.lv
  realm: freight-tracking-app-realm
  resource: freight-tracking-client
  credentials:
    secret: 3Fv47oFkRuqYh2iZDubDJbapzGgdBbGr
  connection-timeout: 5000
  read-timeout: 5000
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false

# OpenAPI Server Configuration
springdoc:
  server:
    prod:
      url: https://api.degra.lv
