spring:
  config:
    import: optional:classpath:application-shared-dev.yaml

server:
  port: 8080

app:
  security:
    allowed-origins: "http://localhost:8081"

# OpenAPI Server Configuration
springdoc:
  server:
    dev:
      url: http://localhost:8080