spring:
  config:
    import: optional:classpath:application-shared-${spring.profiles.active}.yaml

server:
  port: 8080

app:
  security:
    allowed-origins: "http://localhost:8081"


keycloak:
  auth-server-url: https://route.degra.lv
  realm: freight-tracking-app-realm
  resource: freight-tracking-client
  credentials:
    secret: 3Fv47oFkRuqYh2iZDubDJbapzGgdBbGr
  connection-timeout: 5000
  read-timeout: 5000
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false

# OpenAPI Server Configuration
springdoc:
  server:
    prod:
      url: https://usermanager.degra.lv
