spring:
  application:
    name: usermanager
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  show-actuator: false
  server:
    dev:
      url: http://localhost:8080
    test:
      url: https://test-usermanager.degra.lv
    prod:
      url: https://usermanager.degra.lv

# Logging configuration with relative path
logging:
  file:
    name: Logs/usermanager.log
  level:
    root: info
    lv.degra.accounting.company: info
    org.hibernate.SQL: info
