spring:
  config:
    import: optional:classpath:application-shared-${spring.profiles.active}.yaml

server:
  port: 8080

app:
  security:
    allowed-origins: "*"

keycloak:
  auth-server-url: https://route.degra.lv
  realm: degra-test-realm
  resource: freight-tracking-client
  credentials:
    secret: LfJVcO6ArZHzxl0J9YoLj8jdQOYxxiki
  connection-timeout: 5000
  read-timeout: 5000
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false

# OpenAPI Server Configuration
springdoc:
  server:
    test:
      url: https://test-usermanager.degra.lv
