spring:
  application:
    name: freighttracking
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


logging:
  file:
    name: Logs/freighttracking.log
  level:
    root: info
    lv.degra.accounting.freighttracking: info
    org.hibernate.SQL: info
