logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO
    org.springframework: INFO
    org.springframework.jdbc.datasource: INFO
    com.zaxxer.hikari: INFO

#app:
#  security:
#    allowed-origins: "×"