spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/degra_dev?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
  main:
    allow-bean-definition-overriding: true
server:
  port: 8084

app:
  security:
    allowed-origins: "×"