spring:
  config:
    import: optional:file:../shared-resources/application-shared.yaml
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.security: DEBUG
