spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/degra_dev?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
server:
  port: 8084

#logging:
#  level:
#    ROOT: INFO
    #liquibase: INFO
    #org.hibernate.SQL: INFO
    #org.hibernate.envers: INFO
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework: INFO
    #org.springframework.jdbc.datasource: INFO
    #com.zaxxer.hikari: INFO