server:
  port: 8298

app:
  security:
    allowed-origins: "http://localhost:8081,http://localhost:8080"

spring:
  config:
    import: optional:classpath:application-shared-${spring.profiles.active}.yaml