version: '3.8'

services:
  usermanager:
    build:
      context: ..
      dockerfile: usermanager/Dockerfile
    container_name: usermanager-app
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${KEYCLOAK_RESOURCE}
      - KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS=true
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "${APP_PORT}:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
