databaseChangeLog:
  - changeSet:
      id: AddConfig
      author: Kaspars Batrags
      changes:
        - createTable:
            tableName: config
            columns:
              - column:
                  name: key
                  type: varchar(30)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: value
                  type: varchar(200)
                  constraints:
                    nullable: false
