databaseChangeLog:
  - changeSet:
      id: AddConfigDocumentSeries
      author: Kaspars Batrags
      preConditions:
        - onFail: MARK_RAN
        - sqlCheck:
            expectedResult: 0
            sql: SELECT COUNT(*) FROM config WHERE key = 'BILL_SERIES'
      changes:
        - insert:
            tableName: config
            columns:
              - column:
                  name: key
                  value: BILL_SERIES
              - column:
                  name: value
                  value: XXX
  - changeSet:
      id: AddConfigVatPercents
      author: Kaspars Batrags
      preConditions:
        - onFail: MARK_RAN
        - sqlCheck:
            expectedResult: 0
            sql: SELECT COUNT(*) FROM config WHERE key = 'DEFAULT_VAT_PERCENTS'
      changes:
        - insert:
            tableName: config
            columns:
              - column:
                  name: key
                  value: DEFAULT_VAT_PERCENTS
              - column:
                  name: value
                  value: 21

  - changeSet:
      id: AddAddressRegistryLink
      author: Kaspars Batrags
      preConditions:
        - onFail: MARK_RAN
        - sqlCheck:
            expectedResult: 0
            sql: SELECT COUNT(*) FROM config WHERE key = 'ADDRESS_DATA_LINK'
      changes:
        - insert:
            tableName: config
            columns:
              - column:
                  name: key
                  value: ADDRESS_DATA_LINK
              - column:
                  name: value
                  value: https://data.gov.lv/dati/dataset/0c5e1a3b-0097-45a9-afa9-7f7262f3f623/resource/1d3cbdf2-ee7d-4743-90c7-97d38824d0bf/download/aw_csv.zip

  - changeSet:
      id: AddCompanyRegistryLink
      author: Kaspars Batrags
      preConditions:
        - onFail: MARK_RAN
        - sqlCheck:
            expectedResult: 0
            sql: SELECT COUNT(*) FROM config WHERE key = 'COMPANY_DATA_LINK'
      changes:
        - insert:
            tableName: config
            columns:
              - column:
                  name: key
                  value: COMPANY_DATA_LINK
              - column:
                  name: value
                  value: https://dati.ur.gov.lv/register/register.csv