services:
  company-backend:
    build:
      context: ..
      dockerfile: company/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${KEYCLOAK_RESOURCE}
      - KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS=true
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - APP_SECURITY_ALLOWED_ORIGINS=${APP_SECURITY_ALLOWED_ORIGINS}
    ports:
      - "${APP_PORT}:8085"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
