spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/degra_dev?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15

# Logging configuration with relative path
logging:
  file:
    name: Logs/company-dev.log
  level:
    root: debug
    lv.degra.accounting.company: debug
    org.hibernate.SQL: debug