spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://104.248.195.223:5432/degra_test?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: degra_test
    password: XHlPqtbx84WZhs6b9it
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15

keycloak:
  auth-server-url: https://route.degra.lv
  realm: degra-test-realm
  resource: freight-tracking-client
  credentials:
    secret: LfJVcO6ArZHzxl0J9YoLj8jdQOYxxiki
  connection-timeout: 5000
  read-timeout: 5000
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false

# Logging configuration with relative path
logging:
  file:
    name: Logs/${spring.application.name}-test.log
  level:
    root: info
    lv.degra.accounting.company: info
    org.hibernate.SQL: info
