spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/degra_dev?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15

server:
  port: 8085