spring:
server:
  port: 8084
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

application:
  server-url: http://localhost:8083/
  company-download-cron: 0 0 2 * * ?
