spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-company-master.yaml
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

application:
  server-url: http://localhost:8083/
  company-download-cron: 0 0 2 * * ?
