spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8085

application:
  server-url: http://localhost:8085/
  company-download-cron: 0 0 2 * * ?
