spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15

server:
  port: 8085

app:
  security:
    allowed-origins: "*"

logging:
  level:
    ROOT: INFO