server:
  port: 8080

spring:
  datasource:
    initialize: false
  jpa:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://route.degra.lv/realms/freight-tracking-app-realm

keycloak:
  auth-server-url: https://route.degra.lv
  realm: freight-tracking-app-realm
  resource: backend-service
  credentials:
    secret: 3Fv47oFkRuqYh2iZDubDJbapzGgdBbGr

logging:
  level:
    org.springframework.beans.factory: DEBUG