server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://route.degra.lv/realms/freight-tracking-app-realm

keycloak:
  auth-server-url: https://route.degra.lv
  realm: freight-tracking-app-realm
  resource: backend-service
  credentials:
    secret: <client-secret>

logging:
  level:
    org.springframework.beans.factory: DEBUG