spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-desktop-master.yaml
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    show-sql: true
    properties:
      org.hibernate.envers.audit_table_suffix: _aud
      org.hibernate.envers.revision_field_name: revision_id
      org.hibernate.envers.revision_type_field_name: revision_type
  jmx:
    enabled: false